### ISSUE TITLE
  Unhandled match case true

### ISSUE THREAD

**Issue by donejeh** [hypnodev/openapi-generator#3]
So i guess after trying to install the package if i want to generate the doc i get this error

$ php artisan openapi:generator api --output=storage/openapi.yaml

OpenApi specification will be generated in storage/openapi.yaml
Generating OpenApi specification...

   UnhandledMatchError 

  Unhandled match case true

  at vendor\hypnodev\openapi-generator\src\DefinitionFile.php:170
    166▕             $parameterName = $parameter->getName();
    167▕             $allowsNull = $parameter->allowsNull();
    168▕             $parameterIn = match (true) {
    169▕                 $parameterType === 'int', class_exists($parameterType) => 'path',
  ➜ 170▕                 $parameterType === 'string' => 'query'
    171▕             };
    172▕
    173▕             if ($parameterType === null) {
    174▕                 throw new DefinitionException("[$method->class@$method->name] Parameter [$parameterName] has no type.");

  1   vendor\hypnodev\openapi-generator\src\DefinitionFile.php:119
      Hypnodev\OpenapiGenerator\DefinitionFile::createParameters(Object(ReflectionMethod))

  2   vendor\hypnodev\openapi-generator\src\DefinitionFile.php:66
      Hypnodev\OpenapiGenerator\DefinitionFile::createPathEntry(Object(Illuminate\Routing\Route))

![image](https://github.com/hypnodev/openapi-generator/assets/14345639/94b19d27-becf-44cf-989d-e356b1678386)

**Comment by hypnodev** [comment]
fixed in #2

**Comment by donejeh** [comment]
php

$ php -v
PHP 8.2.7 (cli) (built: Jun  7 2023 10:25:38) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
    
  $ php artisan openapi:generator api --output=storage/openapi.yaml


OpenApi specification will be generated in storage/openapi.yaml
Generating OpenApi specification...

   Error 

  Class "PHPStan\PhpDocParser\Lexer\Lexer" not found

  at vendor\hypnodev\openapi-generator\src\DefinitionFile.php:456
    452▕
    453▕     private function parseQueryFromMethodDocComment(string $doc, array &$parameters): void
    454▕     {
    455▕         // Create necessary parser instances
  ➜ 456▕         $lexer = new Lexer();
    457▕         $constExprParser = new ConstExprParser();
    458▕         $phpDocParser = new PhpDocParser(
    459▕             new TypeParser($constExprParser),
    460▕             $constExprParser

  1   vendor\hypnodev\openapi-generator\src\DefinitionFile.php:149
      Hypnodev\OpenapiGenerator\DefinitionFile::parseQueryFromMethodDocComment("/**
     * logout
     *
     * @param  mixed $request
     * @return void
     */")

  2   vendor\hypnodev\openapi-generator\src\DefinitionFile.php:119
      Hypnodev\OpenapiGenerator\DefinitionFile::createParameters(Object(ReflectionMethod))



![image](https://github.com/hypnodev/openapi-generator/assets/14345639/13120318-d20c-4ac5-91cb-3e2a5029eba0)
