### ISSUE TITLE
[Feature Request] Implementing Route filtering by prefix

### ISSUE THREAD

**Issue by Carnicero90** [hypnodev/openapi-generator#5]
I generally think that filtering by route prefix would be a better option, since I could actually want to generate a yaml file just for a specific subset of my api routes (i.e. _/api/v2_ and exclude _/api/v1_), even though they don't necessarily have any different middleware. Besides, as fare as I notice, the **prefix** option is currently unused. 
I can gladly implement it, I'm just asking before submitting any pr since you may not agree that filtering by prefix would be a better option (for whatever reason).

**Comment by hypnodev** [comment]
Yes, you can go for sure!
